<?php

namespace plugin\ai\app\model;

use plugin\admin\app\model\Base;

/**
 * @property integer $roleId 主键(主键)
 * @property string $name 名称
 * @property string $avatar 头像
 * @property string $desc 简介
 * @property string $rolePrompt 角色提示
 * @property string $greeting 问候语
 * @property string $model 模型
 * @property integer $contextNum 上下文数
 * @property integer $maxTokens 最大tokens
 * @property mixed $temperature 温度
 * @property integer $preinstalled 预安装
 * @property integer $installed 安装量
 * @property integer $category 分类
 */
class AiRole extends Base
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'ai_roles';

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'roleId';
    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * @param $column
     * @param $amount
     * @param array $extra
     * @return false|int
     */
    public function increment($column, $amount = 1, array $extra = [])
    {
        return parent::increment($column, $amount, $extra); // TODO: Change the autogenerated stub
    }
    
    
}
